BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `link` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`shortlink`	TEXT NOT NULL UNIQUE,
	`url`	TEXT NOT NULL,
	`created`	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`counter`	INTEGER
);
CREATE TABLE IF NOT EXISTS `config` (
	`key`	TEXT NOT NULL,
	`value`	TEXT,
	PRIMARY KEY(`key`)
);
COMMIT;
